name: Deploy
on: push

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: deliverybot/helm@master
      with:
        release: 'crypto-api'
        namespace: 'default'
        chart: './k8s-helm/crypto-api'
        token: '${{ github.token }}'
        value_files: "values.yaml"
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}' 

      # uses: peymanmortazavi/eks-helm-deploy@v2
      # with:
      #   aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
      #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   aws-region: us-east-2
      #   cluster-name: crypto-api-eks
      #   cluster-role-arn: arn:aws:iam::959068696076:role/crypto-api-eks2022020709502244020000000c
      #   chart-path: ./k8s-helm/crypto-api
      #   config-files: ./k8s-helm/crypto-api/value.yaml
      #   namespace: default
      #   name: crypto-api-demo