name: Deploy
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        release: 'crypto-api'
        namespace: 'default'
        chart: './k8s-helm/crypto-api'
        token: '${{ github.token }}'
        value_files: "values.yaml"
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}' 
