name: Deploy
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'peymanmortazavi/eks-helm-deploy@v1'
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        cluster-name: crypto-api-eks
        config-files: ./k8s-helm/crypto-api/values.yaml
        namespace: default
        name: crypto-api-demo
