name: Test MR Action
on:
  push:
    branches:
      - test

jobs:
  generate-documentation:
    runs-on: ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update main branch
      uses: morbalint/git-merge-action@v1
      with:
        target: 'main'
        source: 'test'
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        strategy_options: 'ours'
